#!/usr/bin/env bash
# ── Trackify Full-Stack Docker Helper ──────────
# Quick compose the entire stack for local testing.
#
# Usage:
#   ./scripts/docker-fullstack.sh          # = up (default)
#   ./scripts/docker-fullstack.sh up       # build + start + migrate + seed
#   ./scripts/docker-fullstack.sh down     # stop and remove containers
#   ./scripts/docker-fullstack.sh restart  # down then up
#   ./scripts/docker-fullstack.sh logs     # tail all service logs
#   ./scripts/docker-fullstack.sh status   # show container status + health
#   ./scripts/docker-fullstack.sh reset    # nuke volumes and rebuild from scratch
#   ./scripts/docker-fullstack.sh health   # hit /health endpoints

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.local"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"

# ── Colors ─────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[error]${NC} $*" >&2; }

# ── Ensure .env.local exists ───────────────────
ensure_env() {
  if [[ -f "$ENV_FILE" ]]; then
    return
  fi

  warn ".env.local not found — creating with dev defaults..."
  cat > "$ENV_FILE" <<'ENVEOF'
# Trackify local development environment
# Generated by scripts/docker-fullstack.sh

# ── PostgreSQL ────────────────────────────────
POSTGRES_DB=trackify
POSTGRES_USER=trackify
POSTGRES_PASSWORD=trackify
POSTGRES_PORT=5432

# ── Prisma (host-side, for CLI commands) ──────
DATABASE_URL=postgresql://trackify:trackify@localhost:5432/trackify

# ── API ───────────────────────────────────────
API_PORT=3010
API_HOST=0.0.0.0
CORS_ORIGIN=http://localhost:5173
JWT_SECRET=dev-jwt-secret-change-in-production

# ── Web ───────────────────────────────────────
WEB_PORT=5173
VITE_API_BASE_URL=http://localhost:3010

# ── Seed user (filled automatically by db:seed) ─
# VITE_SEED_USER_ID=
ENVEOF

  ok "created $ENV_FILE with dev defaults"
  echo -e "   ${YELLOW}Review and adjust if needed before first run.${NC}"
}

# ── Docker compose wrapper ─────────────────────
dc() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile full "$@"
}

dc_no_profile() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

# ── Wait for PostgreSQL healthy ────────────────
wait_postgres() {
  info "waiting for PostgreSQL to become healthy..."
  local attempts=0
  local max_attempts=60

  while [[ $attempts -lt $max_attempts ]]; do
    local status
    status=$(docker inspect --format='{{.State.Health.Status}}' trackify-postgres 2>/dev/null || echo "missing")
    if [[ "$status" == "healthy" ]]; then
      ok "PostgreSQL is healthy"
      return 0
    fi
    attempts=$((attempts + 1))
    printf "\r  waiting... (%d/%d) [status: %s]" "$attempts" "$max_attempts" "$status"
    sleep 2
  done

  echo
  err "PostgreSQL did not become healthy within $((max_attempts * 2))s"
  err "Check logs: docker logs trackify-postgres"
  return 1
}

# ── Run Prisma migrate + seed ──────────────────
run_migrate_seed() {
  info "running Prisma generate..."
  (cd "$ROOT_DIR" && pnpm db:generate) || {
    err "prisma generate failed"
    return 1
  }

  info "running Prisma migrate..."
  (cd "$ROOT_DIR" && pnpm db:migrate) || {
    err "prisma migrate failed"
    return 1
  }

  info "seeding database..."
  local seed_output
  seed_output=$(cd "$ROOT_DIR" && pnpm db:seed 2>&1) || {
    err "db:seed failed"
    echo "$seed_output"
    return 1
  }

  local user_id
  user_id=$(echo "$seed_output" | grep -oE '[a-z][a-z0-9]{20,}' | head -1 || true)

  if [[ -n "$user_id" ]]; then
    if grep -q '^VITE_SEED_USER_ID=' "$ENV_FILE" 2>/dev/null; then
      sed -i '' "s|^VITE_SEED_USER_ID=.*|VITE_SEED_USER_ID=$user_id|" "$ENV_FILE"
    elif grep -q '^# VITE_SEED_USER_ID=' "$ENV_FILE" 2>/dev/null; then
      sed -i '' "s|^# VITE_SEED_USER_ID=.*|VITE_SEED_USER_ID=$user_id|" "$ENV_FILE"
    else
      echo "VITE_SEED_USER_ID=$user_id" >> "$ENV_FILE"
    fi
    ok "seed user id: $user_id (written to .env.local)"
  else
    warn "could not extract seed user id from output:"
    echo "$seed_output"
    warn "manually set VITE_SEED_USER_ID in .env.local"
  fi

  ok "database ready"
}

# ── Commands ───────────────────────────────────

cmd_up() {
  ensure_env

  echo -e "\n${BOLD}Trackify Full-Stack Docker${NC}"
  echo -e "─────────────────────────────────\n"

  info "starting PostgreSQL..."
  dc_no_profile up -d postgres

  wait_postgres
  run_migrate_seed

  info "building and starting api + web..."
  dc up -d --build

  echo -e "\n─────────────────────────────────"

  sleep 3
  cmd_status

  echo -e "\n${BOLD}Endpoints:${NC}"
  local api_port web_port
  api_port=$(grep '^API_PORT=' "$ENV_FILE" | cut -d= -f2 || echo "3010")
  web_port=$(grep '^WEB_PORT=' "$ENV_FILE" | cut -d= -f2 || echo "5173")
  echo -e "  Web:     ${GREEN}http://localhost:${web_port}${NC}"
  echo -e "  API:     ${GREEN}http://localhost:${api_port}${NC}"
  echo -e "  Health:  ${GREEN}http://localhost:${api_port}/health${NC}"
  echo -e "\n  Logs:    ${CYAN}./scripts/docker-fullstack.sh logs${NC}"
  echo -e "  Stop:    ${CYAN}./scripts/docker-fullstack.sh down${NC}"
  echo ""
}

cmd_down() {
  info "stopping all containers..."
  dc down
  ok "all containers stopped"
}

cmd_restart() {
  cmd_down
  echo ""
  cmd_up
}

cmd_logs() {
  dc logs -f --tail=100
}

cmd_status() {
  echo -e "${BOLD}Container Status:${NC}"
  dc_no_profile ps -a --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || dc_no_profile ps -a
  dc ps -a --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || dc ps -a
}

cmd_reset() {
  warn "this will DELETE all data volumes and rebuild from scratch"
  read -rp "Continue? [y/N] " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    info "aborted"
    return
  fi

  info "stopping containers and removing volumes..."
  dc down -v
  ok "volumes removed"

  echo ""
  cmd_up
}

cmd_health() {
  local api_port
  api_port=$(grep '^API_PORT=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "3010")
  local web_port
  web_port=$(grep '^WEB_PORT=' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || echo "5173")

  echo -e "${BOLD}Health Checks:${NC}\n"

  printf "  API  (/health)  ... "
  local api_res
  if api_res=$(curl -sf "http://localhost:${api_port}/health" 2>/dev/null); then
    echo -e "${GREEN}OK${NC}  $api_res"
  else
    echo -e "${RED}FAIL${NC}  (is the api container running?)"
  fi

  printf "  Web  (/)        ... "
  local web_code
  if web_code=$(curl -sf -o /dev/null -w "%{http_code}" "http://localhost:${web_port}/" 2>/dev/null); then
    if [[ "$web_code" == "200" ]]; then
      echo -e "${GREEN}OK${NC}  HTTP $web_code"
    else
      echo -e "${YELLOW}WARN${NC}  HTTP $web_code"
    fi
  else
    echo -e "${RED}FAIL${NC}  (is the web container running?)"
  fi

  printf "  PostgreSQL      ... "
  local pg_status
  pg_status=$(docker inspect --format='{{.State.Health.Status}}' trackify-postgres 2>/dev/null || echo "missing")
  if [[ "$pg_status" == "healthy" ]]; then
    echo -e "${GREEN}OK${NC}  $pg_status"
  else
    echo -e "${RED}FAIL${NC}  $pg_status"
  fi

  echo ""
}

# ── Main ───────────────────────────────────────
main() {
  local cmd="${1:-up}"

  case "$cmd" in
    up)       cmd_up ;;
    down)     cmd_down ;;
    restart)  cmd_restart ;;
    logs)     cmd_logs ;;
    status)   cmd_status ;;
    reset)    cmd_reset ;;
    health)   cmd_health ;;
    -h|--help|help)
      echo "Usage: $0 [up|down|restart|logs|status|reset|health]"
      echo ""
      echo "Commands:"
      echo "  up        Build + start postgres/api/web + migrate + seed (default)"
      echo "  down      Stop and remove containers"
      echo "  restart   Down then up"
      echo "  logs      Tail all service logs"
      echo "  status    Show container status"
      echo "  reset     Nuke volumes and rebuild from scratch"
      echo "  health    Hit /health endpoints"
      ;;
    *)
      err "unknown command: $cmd"
      echo "Run '$0 --help' for usage"
      exit 1
      ;;
  esac
}

main "$@"
